name:                Van-der-Silk-Logo
version:             0.1.0.0
homepage:            https://github.com/silky/fashion/Van-der-Silk-Logo
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           2017 Noon van der Silk
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - colour
  - diagrams
  - diagrams-cairo
  - diagrams-contrib
  - diagrams-lib
  - palette

executables:
  nvds-logo:
    source-dirs:      src
    main:             Main.hs
