name:                Tilings-I95
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/Tilings-I95#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-cairo
  - diagrams-contrib
  - diagrams-lib
  - nvds-lib
  - random
  - split


executables:
  Tilings-I95:
    source-dirs:      src
    main:             Main.hs
