name:                Abelian-Sandpile
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/silky/fashion/Abelian-Sandpile#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           2018 Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - JuicyPixels
  - JuicyPixels-repa
  - primitive
  - repa
  - text

executables:
  Abelian-Sandpile:
    source-dirs:      src
    main:             Main.hs
